version: '3.4'

services:
  authenticationapi:
    image: authenticationapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 44433:44433
    networks: 
      - backend

networks: 
  backend:
    external: 
      name: backend
